.PHONY: all clean

all:
	$(MAKE) -C common
	$(MAKE) -C common_letkc
	$(MAKE) -C ensmodel
	$(MAKE) -C obs
	$(MAKE) -C letkf
	$(MAKE) -C letkc

clean:
	$(MAKE) -C common            clean
	$(MAKE) -C common_letkc      clean
	$(MAKE) -C ensmodel          clean
	$(MAKE) -C obs               clean
	$(MAKE) -C letkf             clean
	$(MAKE) -C letkc             clean
